# Start with Alpine Linux
FROM oven/bun:alpine as base
WORKDIR /usr/src/app

USER root

RUN apk update && apk upgrade && apk add --no-cache bash

# Install latest Chromium package
RUN apk upgrade --no-cache --available \
    && apk add --no-cache \
      chromium-swiftshader \
      ttf-freefont \
      font-noto-emoji \
    && apk add --no-cache \
      --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
      font-wqy-zenhei

# Add Chrome as a user
RUN adduser -D chrome \
    && chown -R chrome:chrome /usr/src/app

# Run Chrome as non-privileged
USER chrome

# Set environment variables for headless Chrome
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/

# Autorun chrome headless
ENV CHROMIUM_FLAGS="--disable-software-rasterizer --disable-dev-shm-usage"

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
COPY package.json /usr/src/app/
RUN bun install

# install with --production (exclude devDependencies)
COPY package.json /usr/src/app/
RUN bun install

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /usr/src/app/node_modules node_modules
COPY . .

# copy production dependencies and source code into final image
FROM base AS release
COPY --from=install /usr/src/app/node_modules node_modules
COPY --from=prerelease /usr/src/app/ .

# run the app
USER chrome
EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "index.ts" ]