name: build
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SUBMODULES_ACCESS }}
          submodules: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install pnpm
        run: npm i pnpm@latest -g
      # - name: Setup npmrc
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH }}" > .npmrc
      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: install dependencies
        run: pnpm install
      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1.4.1
      #   with:
      #    title: 'chore: version packages'
      #     commit: 'chore: version packages'
      #     version: pnpm changeset:version
      #     publish: pnpm changeset:release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_AUTH }}